version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.7
    container_name: mysql-redcoin
    ports:
      - "1805:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123mudar
      - MYSQL_DATABASE=redcoin
  redis:
    image: redis
    command: redis-server --requirepass RedisRedCoinApi
    ports: 
      - "6379:6379"