version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123mudar
      - MYSQL_DATABASE=bitcoinDB